name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign new issues to ISAR project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened' && github.event_name == "issues"
      with:
        project: 'https://github.com/orgs/equinor/projects/85'
        column_name: 'Todo'
        
    - name: Assign new pull requests to ISAR project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened' && github.event_name == "pull_request_target"
      with:
        project: 'https://github.com/orgs/equinor/projects/85'
        column_name: 'Review'

